config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homepages#index"

  resources :sessions, only: [:create, :show], param: :token
  get "/sign_in", to: "sessions#new", as: "sign_in"
  delete "/sign_out", to: "sessions#destroy", as: "sign_out"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login_token.rb
require "securerandom"

class LoginToken < ApplicationRecord
  belongs_to :user

  before_create :generate_token_and_valid_until

  def self.active
    where("valid_until > ?", Time.current)
  end

  def generate_token_and_valid_until
    self.token = SecureRandom.hex(32)
    self.valid_until = valid_until || 10.minutes.from_now
  end

  def to_param
    token
  end
end

app/models/session.rb
class Session
  include ActiveModel::Model

  attr_accessor :email
end

app/models/user.rb
class User < ApplicationRecord
  has_many :login_tokens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :warning, :success

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  private

  def record_not_found
    render plain: "404 Not Found", status: 404
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: login_params[:email])

    if user.present?
      login_token = user.login_tokens.create!
      UserLoginLinkMailer.login_email(user: user, login_token: login_token).deliver_later
    end

    redirect_to root_path, success: "Sent! Check your email for a magic link to log in."
  end

  def show
    token = LoginToken.active.find_by(token: params[:token])

    if token.present?
      session[:user_id] = token.user_id
      redirect_to root_path, success: "Successfully logged in."
    else
      redirect_to sign_in_path, notice: "Please request a magic link to login."
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, success: "Successfully logged out."
  end

  private

  def login_params
    params.require(:session).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("error", "notice", "success")
  end
end

app/views/homepages/index.html.erb
<p class="font-sans">Hello, world.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimmingForum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

    <body class="bg-gray-100">
    <div class="lg:container lg:mx-auto h-24 flex items-center justify-between p-5">
      <div>
        <p class="text-3xl font-semibold text-black">SWSF Online</p>
        <span class="text-gray-600 italic text-sm">Star Wars Simming Forum</span>
      </div>

      <% if current_user %>
        <div class="space-x-2 text text-">
          <%= link_to "Sign Out", sign_out_path, method: :delete %>
        </div>
      <% else %>
        <div class="space-x-2 text text-">
          <%= link_to "Sign In", sign_in_path %>
          <a class="text-base" href="#">Sign Up</a>
        </div>
      <% end %>
    </div>

    <%= render "shared/flashes" %>

    <main class="lg:container lg:mx-auto p-5 mt-12">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <div class="lg:container lg:mx-auto p-5">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>">
        <span class="block sm:inline"><%= value %></span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
          <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <title>Close</title>
            <path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/>
          </svg>
        </span>
      </div>
    <% end -%>
  </div>
<% end %>